# Generated by Django 4.2 on 2023-07-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=30)),
                ('message', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='contact_us',
        ),
    ]
