# Generated by Django 4.2 on 2023-07-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0004_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(max_length=20),
        ),
    ]
