# Generated by Django 4.2 on 2023-07-08 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0006_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
