# Generated by Django 4.2 on 2023-08-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0007_remove_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('eml', models.CharField(max_length=10)),
                ('psw', models.IntegerField(max_length=5)),
            ],
        ),
    ]
