# Generated by Django 4.2.5 on 2023-09-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0008_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
